test server conn1

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,13 +31,15 @@ jobs:
 #        run: mvn clean package
 
       - name: Rename the artifact
-        run: cp target/ci-cd-test-0.0.1-SNAPSHOT.jar ci-cd-test-${{ github.sha }}.jar
+        #run: cp target/ci-cd-test-0.0.1-SNAPSHOT.jar ci-cd-test-${{ github.sha }}.jar
+        run: cp target/ci-cd-test-0.0.1-SNAPSHOT.jar ci-cd-test.jar
 
       - name: Save the artifact
         uses: actions/upload-artifact@v3
         with:
           name: ci-cd-test
-          path: ci-cd-test-${{ github.sha }}.jar
+#          path: ci-cd-test-${{ github.sha }}.jar
+          path: ci-cd-test.jar
 
   deploy:
     runs-on: self-hosted
@@ -48,5 +50,29 @@ jobs:
         with:
           name: ci-cd-test
 
-      - name: Fake deploy
+      - name: Wait for SSH
+        run: |
+          while ! nc -w5 -z ${{ secrets.SSH_HOST }} 22; do
+                  sleep 1
+                  echo "SSH not available..."
+          done; echo "SSH ready!"
+
+      - name: Stop App
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USER }}
+          key: ${{ secrets.SSH_KEY }}
+          script: |
+#            pid=`ps aux | grep "[c]icd-demo.jar" | awk '{print $2}'`
+#            if [ "$pid" == "" ]; then
+#              echo "Process not found"
+#            else
+#              kill -9 $pid
+#            fi
+            if [ ! -d app ]; then 
+                    mkdir app
+            fi
+
+      - name: deploy
         run: ls ci-cd-test*.jar
